name: Solar System Workflow
on:
  push:
    branches:
      - branch-b
  workflow_dispatch: 
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node JS
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Dependencies
        run: npm install --no-audit
