name: Solar System Workflow
on:
  push:
    branches:
      - branch-b
  workflow_dispatch: 
jobs:
  unit-testing:
    runs-on: { { matrix.os_version } }
    strategy:
      matrix:
        os_version: [ubuntu-latest, macos-latest]
        nodejs_versions: [20, 21, 22]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node JS
        uses: actions/setup-node@v4
        with:
          node-version: { { matrix.nodejs_versions } }

      - name: Install Dependencies
        run: npm install --no-audit
